#!/usr/bin/env bash
# Generated by Unclaimed Bloom.
# Do not edit unless you enjoy losing arguments with future automation.
#
# Target: gum
# Theme: Unclaimed Bloom / gummy

# ------------------------------------------------------------------------------
# Raw theme colors
# ------------------------------------------------------------------------------

export GUM_UB_BACKGROUND="{{background}}"
export GUM_UB_SURFACE="{{surface}}"
export GUM_UB_SURFACE_VARIANT="{{surface_variant}}"
export GUM_UB_PRIMARY="{{primary}}"
export GUM_UB_SECONDARY="{{secondary}}"
export GUM_UB_TERTIARY="{{tertiary}}"
export GUM_UB_ON_BACKGROUND="{{on_background}}"
export GUM_UB_ON_SURFACE="{{on_surface}}"
export GUM_UB_ON_SURFACE_VARIANT="{{on_surface_variant}}"
export GUM_UB_ON_PRIMARY="{{on_primary}}"
export GUM_UB_ERROR="{{error}}"
export GUM_UB_ON_ERROR="{{on_error}}"
export GUM_UB_OUTLINE="{{outline}}"

# ------------------------------------------------------------------------------
# gum input
# ------------------------------------------------------------------------------

export GUM_INPUT_PROMPT="❯ "
export GUM_INPUT_CURSOR_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_INPUT_PROMPT_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="$GUM_UB_ON_SURFACE_VARIANT"
export GUM_INPUT_HEADER_FOREGROUND="$GUM_UB_ON_SURFACE"

# ------------------------------------------------------------------------------
# gum choose
# ------------------------------------------------------------------------------

export GUM_CHOOSE_CURSOR="❯"
export GUM_CHOOSE_CURSOR_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_CHOOSE_HEADER_FOREGROUND="$GUM_UB_ON_SURFACE_VARIANT"
export GUM_CHOOSE_ITEM_FOREGROUND="$GUM_UB_ON_SURFACE_VARIANT"
export GUM_CHOOSE_SELECTED_FOREGROUND="$GUM_UB_ON_SURFACE"

# ------------------------------------------------------------------------------
# gum filter
# ------------------------------------------------------------------------------

export GUM_FILTER_PROMPT="❯ "
export GUM_FILTER_PROMPT_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_FILTER_CURSOR_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_FILTER_MATCH_FOREGROUND="$GUM_UB_TERTIARY"
export GUM_FILTER_SELECTED_FOREGROUND="$GUM_UB_ON_SURFACE"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="$GUM_UB_ON_SURFACE_VARIANT"

# ------------------------------------------------------------------------------
# gum confirm
# ------------------------------------------------------------------------------

export GUM_CONFIRM_PROMPT_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_CONFIRM_SELECTED_FOREGROUND="$GUM_UB_ON_SURFACE"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="$GUM_UB_ON_SURFACE_VARIANT"

# ------------------------------------------------------------------------------
# gum spin
# ------------------------------------------------------------------------------

export GUM_SPIN_SPINNER_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_SPIN_TITLE_FOREGROUND="$GUM_UB_ON_SURFACE_VARIANT"

# ------------------------------------------------------------------------------
# gum table
# ------------------------------------------------------------------------------

export GUM_TABLE_HEADER_FOREGROUND="$GUM_UB_PRIMARY"
export GUM_TABLE_CELL_FOREGROUND="$GUM_UB_ON_SURFACE"
export GUM_TABLE_SELECTED_FOREGROUND="$GUM_UB_ON_SURFACE"
export GUM_TABLE_BORDER_FOREGROUND="$GUM_UB_SURFACE_VARIANT"

# ------------------------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------------------------

gum_ub_box() {
  gum style \
    --border rounded \
    --border-foreground "$GUM_UB_SURFACE_VARIANT" \
    --foreground "$GUM_UB_ON_SURFACE" \
    --padding "1 2" \
    --margin "1 0" \
    "$@"
}

gum_ub_title() {
  gum style \
    --bold \
    --foreground "$GUM_UB_PRIMARY" \
    "$@"
}

gum_ub_muted() {
  gum style \
    --foreground "$GUM_UB_ON_SURFACE_VARIANT" \
    "$@"
}

gum_ub_success() {
  gum style \
    --foreground "$GUM_UB_TERTIARY" \
    "$@"
}

gum_ub_error_box() {
  gum style \
    --border rounded \
    --border-foreground "$GUM_UB_ERROR" \
    --foreground "$GUM_UB_ERROR" \
    --padding "1 2" \
    --margin "1 0" \
    "$@"
}
