import { spawn }              from 'node:child_process';
import { mkdir, writeFile }  from 'node:fs/promises';
import { dirname }           from 'node:path';
import { loadSourceColors }  from '../node/loader.js';
import type { Report, Spore } from '../core/types';

const RECIPE_TOKENS = [
    'background', 'surface', 'surface_variant',
    'primary', 'secondary', 'tertiary',
    'on_background', 'on_surface',
    'outline', 'error',
];

export interface AgsAdapterConfig {
    outputPath:      string;
    sourceColorsPath: string;
    variant:         'dark' | 'light' | 'default';
    postHook?:       string;
}

function renderCss(colors: Record<string, string>): string {
    const lines = [
        '/*',
        ' * CSS Colors',
        ' * Generated by Unclaimed Bloom',
        ' */',
        '',
    ];
    for (const [key, value] of Object.entries(colors).sort(([a], [b]) => a.localeCompare(b))) {
        lines.push(`@define-color ${key} ${value};`);
    }
    lines.push('');
    return lines.join('\n');
}

function runDetached(cmd: string): void {
    const child = spawn('sh', ['-c', cmd], { detached: true, stdio: 'ignore' });
    child.unref();
}

export class AgsAdapter {
    public async apply(spore: Spore, config: AgsAdapterConfig): Promise<Report> {
        const startedAt = new Date().toISOString();

        const missing = RECIPE_TOKENS.filter(k => spore.colors[k] === undefined);
        if (missing.length > 0) {
            throw new Error(`Recipe "${spore.recipe}" is missing tokens: ${missing.join(', ')}`);
        }

        // Start with all source colors, then overlay the recipe-mixed tokens on top
        const sourceColors = await loadSourceColors(config.sourceColorsPath, config.variant);
        const merged = { ...sourceColors, ...spore.colors };

        const css = renderCss(merged);
        await mkdir(dirname(config.outputPath), { recursive: true });
        await writeFile(config.outputPath, css, 'utf8');

        if (config.postHook) runDetached(config.postHook);

        return {
            target:     spore.target,
            profile:    spore.profile,
            recipe:     spore.recipe,
            status:     'ok',
            inputs:     { basePalette: spore.recipe, sourceColorsPath: config.sourceColorsPath },
            outputs:    [config.outputPath],
            warnings:   [],
            errors:     [],
            startedAt,
            finishedAt: new Date().toISOString(),
        };
    }
}
