import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Report, Spore } from '../core/types';

const execFileAsync = promisify(execFile);

const PALETTE_SIZE = 16;

const REQUIRED_TOKENS = [
    'background', 'foreground',
    'cursor_color', 'cursor_text',
    'selection_background', 'selection_foreground',
    ...Array.from({ length: PALETTE_SIZE }, (_, i) => `palette_${i}`),
];

function requireColor(colors: Record<string, string>, key: string, recipe: string): string {
    const value = colors[key];
    if (value === undefined) {
        throw new Error(`Recipe "${recipe}" is missing required token "${key}"`);
    }
    return value;
}

function renderTheme(spore: Spore): string {
    const c = spore.colors;
    const r = (key: string) => requireColor(c, key, spore.recipe);

    const paletteLines = Array.from(
        { length: PALETTE_SIZE },
        (_, i) => `palette = ${i}=${r(`palette_${i}`)}`,
    );

    return [
        '# Generated by Unclaimed Bloom / spore.',
        '# Do not edit this file directly unless you enjoy losing arguments with automation.',
        '',
        `background = ${r('background')}`,
        `foreground = ${r('foreground')}`,
        '',
        `cursor-color = ${r('cursor_color')}`,
        `cursor-text  = ${r('cursor_text')}`,
        '',
        `selection-background = ${r('selection_background')}`,
        `selection-foreground = ${r('selection_foreground')}`,
        '',
        ...paletteLines,
        '',
    ].join('\n');
}

export class GhosttyAdapter {
    public async apply(spore: Spore, outputPath: string): Promise<Report> {
        const startedAt = new Date().toISOString();

        const missing = REQUIRED_TOKENS.filter(k => spore.colors[k] === undefined);
        if (missing.length > 0) {
            throw new Error(
                `Recipe "${spore.recipe}" is missing tokens:\n  ${missing.join(', ')}`,
            );
        }

        const theme = renderTheme(spore);
        await mkdir(dirname(outputPath), { recursive: true });
        await writeFile(outputPath, theme, 'utf8');

        const warnings: string[] = [];
        try {
            await execFileAsync('pkill', ['-SIGUSR2', 'ghostty']);
        } catch {
            warnings.push('ghostty reload skipped (process not found)');
        }

        return {
            target:      spore.target,
            profile:     spore.profile,
            recipe:      spore.recipe,
            status:      'ok',
            inputs:      { basePalette: spore.recipe, sourcePalette: 'matugen' },
            outputs:     [outputPath],
            warnings,
            errors:      [],
            startedAt,
            finishedAt:  new Date().toISOString(),
        };
    }
}
