import { spawn }             from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname }          from 'node:path';
import { loadSourceColors } from '../node/loader.js';
import type { Report, Spore } from '../core/types';

export interface HyprlandAdapterConfig {
    luaPath:          string;
    confPath:         string;
    sourceColorsPath: string;
    variant:          'dark' | 'light' | 'default';
    postHook?:        string;
}

function hexToRgba(hex: string): string {
    return `rgba(${hex.replace('#', '').toLowerCase()}ff)`;
}

function renderLua(colors: Record<string, string>): string {
    const lines = [
        '-- Generated by Unclaimed Bloom',
        '',
        'local C = {',
    ];
    for (const [key, hex] of Object.entries(colors).sort(([a], [b]) => a.localeCompare(b))) {
        lines.push(`  ${key} = "${hexToRgba(hex)}",`);
    }
    lines.push('}', '', '_G.AdartColors = C', 'return C', '');
    return lines.join('\n');
}

function renderConf(colors: Record<string, string>): string {
    const lines = ['# Generated by Unclaimed Bloom', ''];
    for (const [key, hex] of Object.entries(colors).sort(([a], [b]) => a.localeCompare(b))) {
        const stripped = hex.replace('#', '').toLowerCase();
        lines.push(`$${key} = ${hexToRgba(hex)}`);
        lines.push(`$${key}_hex = ${stripped}`);
    }
    lines.push('');
    return lines.join('\n');
}

function runDetached(cmd: string): void {
    const child = spawn('sh', ['-c', cmd], { detached: true, stdio: 'ignore' });
    child.unref();
}

export class HyprlandAdapter {
    public async apply(spore: Spore, config: HyprlandAdapterConfig): Promise<Report> {
        const startedAt = new Date().toISOString();

        const sourceColors = await loadSourceColors(config.sourceColorsPath, config.variant);
        const all = { ...sourceColors, ...spore.colors };

        await mkdir(dirname(config.luaPath),  { recursive: true });
        await mkdir(dirname(config.confPath), { recursive: true });

        await writeFile(config.luaPath,  renderLua(all),  'utf8');
        await writeFile(config.confPath, renderConf(all), 'utf8');

        if (config.postHook) runDetached(config.postHook);

        return {
            target:     spore.target,
            profile:    spore.profile,
            recipe:     spore.recipe,
            status:     'ok',
            inputs:     { basePalette: spore.recipe, sourceColorsPath: config.sourceColorsPath },
            outputs:    [config.luaPath, config.confPath],
            warnings:   [],
            errors:     [],
            startedAt,
            finishedAt: new Date().toISOString(),
        };
    }
}
