import { execFile }           from 'node:child_process';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { dirname, join }     from 'node:path';
import { promisify }         from 'node:util';
import type { Report, Spore } from '../core/types';

const execFileAsync = promisify(execFile);

const REQUIRED_TOKENS = [
    'background', 'surface', 'surface_variant',
    'primary', 'secondary', 'tertiary',
    'on_background', 'on_surface',
    'error',
];

export interface NvimAdapterConfig {
    outputPath: string;
}

function renderLua(colors: Record<string, string>): string {
    return `-- Generated by Unclaimed Bloom. Do not edit by hand.

return {
\tsource = {
\t\timage = "",
\t},

\tcolors = {
\t\tbackground     = "${colors['background']}",
\t\tsurface        = "${colors['surface']}",
\t\tsurface_variant = "${colors['surface_variant']}",

\t\tprimary        = "${colors['primary']}",
\t\tsecondary      = "${colors['secondary']}",
\t\ttertiary       = "${colors['tertiary']}",

\t\ton_background  = "${colors['on_background']}",
\t\ton_surface     = "${colors['on_surface']}",

\t\terror          = "${colors['error']}",
\t},
}
`;
}

async function findNvimSockets(): Promise<string[]> {
    const runtimeDir = process.env['XDG_RUNTIME_DIR']
        ?? `/run/user/${process.getuid?.() ?? 1000}`;
    try {
        const files = await readdir(runtimeDir);
        return files
            .filter(f => /^nvim\.\d+\.\d+$/.test(f))
            .map(f => join(runtimeDir, f));
    } catch {
        return [];
    }
}

async function reloadNvim(sockets: string[]): Promise<void> {
    const cmd = ":lua package.loaded['generated.matugen-colors']=nil; vim.cmd.colorscheme(vim.g.colors_name)\n";
    for (const socket of sockets) {
        try {
            await execFileAsync('nvim', ['--server', socket, '--remote-send', cmd]);
        } catch { /* instance may be busy or shutting down */ }
    }
}

export class NvimAdapter {
    public async apply(spore: Spore, config: NvimAdapterConfig): Promise<Report> {
        const startedAt = new Date().toISOString();

        const missing = REQUIRED_TOKENS.filter(k => spore.colors[k] === undefined);
        if (missing.length > 0) {
            throw new Error(`Recipe "${spore.recipe}" is missing tokens: ${missing.join(', ')}`);
        }

        const lua = renderLua(spore.colors);
        await mkdir(dirname(config.outputPath), { recursive: true });
        await writeFile(config.outputPath, lua, 'utf8');

        const sockets = await findNvimSockets();
        await reloadNvim(sockets);

        return {
            target:     spore.target,
            profile:    spore.profile,
            recipe:     spore.recipe,
            status:     'ok',
            inputs:     { basePalette: spore.recipe },
            outputs:    [config.outputPath],
            warnings:   sockets.length === 0 ? ['no running nvim instances found — reload manually'] : [],
            errors:     [],
            startedAt,
            finishedAt: new Date().toISOString(),
        };
    }
}
