import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname }                    from 'node:path';
import type { Report, Spore }          from '../core/types';

const REQUIRED_TOKENS = ['background', 'background_alt', 'foreground', 'accent1', 'selected', 'active', 'urgent'];

export interface RofiAdapterConfig {
    outputPath:       string;
    wallpaperCachePath?: string;
    backgroundAlpha?: number;   // default 0.75
}

function hexToRgba(hex: string, alpha: number): string {
    const h = hex.replace('#', '');
    const r = parseInt(h.slice(0, 2), 16);
    const g = parseInt(h.slice(2, 4), 16);
    const b = parseInt(h.slice(4, 6), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function renderRasi(c: Record<string, string>, alpha: number, imagePath: string | null): string {
    const imageUrl = imagePath ? `url("${imagePath}", width)` : 'none';
    return [
        '/* Generated by Unclaimed Bloom */',
        '* {',
        '    font:            "GeistMono Nerd Font Propo 13";',
        `    background:      ${hexToRgba(c['background']!, alpha)};`,
        `    background-alt:  ${c['background_alt']!};`,
        `    foreground:      ${c['foreground']!};`,
        `    accent1:         ${c['accent1']!};`,
        `    selected:        ${c['selected']!};`,
        `    active:          ${c['active']!};`,
        `    urgent:          ${c['urgent']!};`,
        `    image:           ${imageUrl};`,
        '}',
        '',
    ].join('\n');
}

export class RofiAdapter {
    public async apply(spore: Spore, config: RofiAdapterConfig): Promise<Report> {
        const startedAt = new Date().toISOString();

        const missing = REQUIRED_TOKENS.filter(k => spore.colors[k] === undefined);
        if (missing.length > 0) {
            throw new Error(`Recipe "${spore.recipe}" is missing rofi tokens: ${missing.join(', ')}`);
        }

        let imagePath: string | null = null;
        if (config.wallpaperCachePath) {
            try {
                imagePath = (await readFile(config.wallpaperCachePath, 'utf8')).trim();
            } catch {
                // no cached wallpaper yet — skip image
            }
        }

        const alpha = config.backgroundAlpha ?? 0.75;
        const rasi  = renderRasi(spore.colors as Record<string, string>, alpha, imagePath);

        await mkdir(dirname(config.outputPath), { recursive: true });
        await writeFile(config.outputPath, rasi, 'utf8');

        return {
            target:     spore.target,
            profile:    spore.profile,
            recipe:     spore.recipe,
            status:     'ok',
            inputs:     { basePalette: spore.recipe },
            outputs:    [config.outputPath],
            warnings:   [],
            errors:     [],
            startedAt,
            finishedAt: new Date().toISOString(),
        };
    }
}
