import { mkdir, writeFile }  from 'node:fs/promises';
import { dirname }           from 'node:path';
import { loadSourceColors }  from '../node/loader.js';
import type { Report, Spore } from '../core/types';

const REQUIRED_TOKENS = ['primary', 'on_primary', 'secondary', 'error'];

export interface SddmAdapterConfig {
    outputPath:       string;
    sourceColorsPath: string;
    variant:          'dark' | 'light' | 'default';
}

function renderConf(c: Record<string, string>): string {
    const t = (key: string) => c[key] ?? '#000000';
    return `# Generated by Unclaimed Bloom for sddm-adart-matugener.
# Based on the config keys used by Keyitdev/sddm-astronaut-theme.
#
# Background note:
# Astronaut expects Background to be a relative path inside the theme directory.
# Therefore this points to a symlink:
#
#   /usr/share/sddm/themes/sddm-adart-matugener/Backgrounds/adart-current.png
#     -> /usr/local/share/sddm-adart-matugener/background.png
#
# Your wallpaper script/sddm-adart-apply updates the real target file.

[General]

# Screen
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

# Font
Font="Open Sans"
FontSize="13"

# Keyboard
KeyboardSize="0.4"

# Shape
RoundCorners="20"

# Locale / time
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

# Header
HeaderText=""

# Background
BackgroundPlaceholder=""
Background="Backgrounds/adart-current.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

# Colors: dark/calm surfaces, primary as accent, footer muted.
HeaderTextColor="${t('on_surface')}"
DateTextColor="${t('on_surface')}"
TimeTextColor="${t('on_surface')}"

FormBackgroundColor="${t('surface_container')}"
BackgroundColor="${t('background')}"
DimBackgroundColor="${t('background')}"

LoginFieldBackgroundColor="${t('surface_container')}"
PasswordFieldBackgroundColor="${t('surface_container')}"

LoginFieldTextColor="${t('on_surface')}"
PasswordFieldTextColor="${t('on_surface')}"

UserIconColor="${t('primary')}"
PasswordIconColor="${t('primary')}"

PlaceholderTextColor="${t('on_surface_variant')}"
WarningColor="${t('error')}"

LoginButtonTextColor="${t('on_primary')}"
LoginButtonBackgroundColor="${t('primary')}"

SystemButtonsIconsColor="${t('on_surface_variant')}"
SessionButtonTextColor="${t('on_surface_variant')}"
VirtualKeyboardButtonTextColor="${t('on_surface_variant')}"

DropdownTextColor="${t('on_surface')}"
DropdownSelectedBackgroundColor="${t('surface_container_highest')}"
DropdownBackgroundColor="${t('surface_container')}"

HighlightTextColor="${t('on_surface')}"
HighlightBackgroundColor="${t('surface_container_highest')}"
HighlightBorderColor="${t('primary')}"

HoverUserIconColor="${t('secondary')}"
HoverPasswordIconColor="${t('secondary')}"
HoverSystemButtonsIconsColor="${t('primary')}"
HoverSessionButtonTextColor="${t('primary')}"
HoverVirtualKeyboardButtonTextColor="${t('primary')}"

# Blur / layout
PartialBlur="true"
FullBlur=""
BlurMax=""
Blur=""

# Important for the original Astronaut look:
# false means no separate dark box behind the form.
HaveFormBackground="false"

FormPosition="center"
VirtualKeyboardPosition="center"

# Visibility
HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

# Login behavior
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

# Translations
TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
`;
}

export class SddmAdapter {
    public async apply(spore: Spore, config: SddmAdapterConfig): Promise<Report> {
        const startedAt = new Date().toISOString();

        const missing = REQUIRED_TOKENS.filter(k => spore.colors[k] === undefined);
        if (missing.length > 0) {
            throw new Error(`Recipe "${spore.recipe}" is missing sddm tokens: ${missing.join(', ')}`);
        }

        const sourceColors = await loadSourceColors(config.sourceColorsPath, config.variant);
        const merged = { ...sourceColors, ...spore.colors };

        await mkdir(dirname(config.outputPath), { recursive: true });
        await writeFile(config.outputPath, renderConf(merged), 'utf8');

        return {
            target:     spore.target,
            profile:    spore.profile,
            recipe:     spore.recipe,
            status:     'ok',
            inputs:     { basePalette: spore.recipe, sourceColorsPath: config.sourceColorsPath },
            outputs:    [config.outputPath],
            warnings:   [],
            errors:     [],
            startedAt,
            finishedAt: new Date().toISOString(),
        };
    }
}
