import { execFile }           from 'node:child_process';
import { mkdir, writeFile }   from 'node:fs/promises';
import { dirname }            from 'node:path';
import { promisify }          from 'node:util';
import { loadSourceColors }   from '../node/loader.js';
import type { Report, Spore } from '../core/types';

const execFileAsync = promisify(execFile);

const REQUIRED_TOKENS = [
    'background', 'surface', 'surface_variant',
    'primary', 'secondary', 'tertiary',
    'on_background', 'on_surface',
    'outline', 'error',
];

export interface SwayncAdapterConfig {
    outputPath:       string;
    sourceColorsPath: string;
    variant:          'dark' | 'light' | 'default';
}

function renderCss(colors: Record<string, string>): string {
    const lines = [
        '/*',
        ' * CSS Colors',
        ' * Generated by Unclaimed Bloom',
        ' */',
        '',
    ];
    for (const [key, value] of Object.entries(colors).sort(([a], [b]) => a.localeCompare(b))) {
        lines.push(`@define-color ${key} ${value};`);
    }
    lines.push('');
    return lines.join('\n');
}

export class SwayncAdapter {
    public async apply(spore: Spore, config: SwayncAdapterConfig): Promise<Report> {
        const startedAt = new Date().toISOString();

        const missing = REQUIRED_TOKENS.filter(k => spore.colors[k] === undefined);
        if (missing.length > 0) {
            throw new Error(`Recipe "${spore.recipe}" is missing swaync tokens: ${missing.join(', ')}`);
        }

        const sourceColors = await loadSourceColors(config.sourceColorsPath, config.variant);
        const merged = { ...sourceColors, ...spore.colors };

        await mkdir(dirname(config.outputPath), { recursive: true });
        await writeFile(config.outputPath, renderCss(merged), 'utf8');

        const warnings: string[] = [];
        try {
            await execFileAsync('swaync-client', ['--reload-css']);
        } catch {
            warnings.push('swaync CSS reload skipped');
        }

        return {
            target:     spore.target,
            profile:    spore.profile,
            recipe:     spore.recipe,
            status:     'ok',
            inputs:     { basePalette: spore.recipe, sourceColorsPath: config.sourceColorsPath },
            outputs:    [config.outputPath],
            warnings,
            errors:     [],
            startedAt,
            finishedAt: new Date().toISOString(),
        };
    }
}
