-- Generated by Unclaimed Bloom (Deno template). Do not edit by hand.

return {
	source = {
		image = "",
	},

	colors = {
		background      = "{{background}}",
		surface         = "{{surface}}",
		surface_variant = "{{surface_variant}}",

		primary         = "{{primary}}",
		secondary       = "{{secondary}}",
		tertiary        = "{{tertiary}}",

		on_background   = "{{on_background}}",
		on_surface      = "{{on_surface}}",

		error           = "{{error}}",
	},
}
