#!/usr/bin/env python3
"""
matugen-ghostty-moonmix.py

Generate a Ghostty theme by mixing Tokyonight Moon with a Matugen palette.

Why this exists:
    Matugen alone can make a terminal follow the wallpaper.
    Tokyonight Moon alone can make a terminal readable and tasteful.
    This script tries to keep both. A rare diplomatic success.

Expected input:
    A small JSON file generated by Matugen from ghostty-palette.json.template.

Example:
    matugen-ghostty-moonmix.py \
      --palette ~/.cache/matugen/ghostty-palette.json \
      --output ~/.config/ghostty/themes/MatugenMoon
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TOKYO_MOON = {
    # Tokyonight Moon-ish base colors.
    # These are intentionally hardcoded: they are the stable spine of the theme.
    "bg": "#222436",
    "bg_dark": "#1e2030",
    "bg_highlight": "#2f334d",
    "fg": "#c8d3f5",
    "fg_dark": "#828bb8",
    "comment": "#636da6",

    "blue": "#82aaff",
    "cyan": "#86e1fc",
    "green": "#c3e88d",
    "yellow": "#ffc777",
    "orange": "#ff966c",
    "red": "#ff757f",
    "magenta": "#c099ff",
    "purple": "#fca7ea",
}


def clamp(value: float, low: int = 0, high: int = 255) -> int:
    return max(low, min(high, round(value)))


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    value = hex_color.strip().lstrip("#")
    if len(value) != 6:
        raise ValueError(f"Expected #RRGGBB color, got {hex_color!r}")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def mix(base: str, tint: str, tint_weight: float) -> str:
    """
    Mix two colors in simple sRGB.

    tint_weight:
        0.0 = pure base
        1.0 = pure tint

    This is deliberately simple because terminal palettes should be predictable.
    Future Adam may replace this with Oklab and then complain about it later.
    """
    br, bg, bb = hex_to_rgb(base)
    tr, tg, tb = hex_to_rgb(tint)

    return rgb_to_hex((
        clamp(br * (1 - tint_weight) + tr * tint_weight),
        clamp(bg * (1 - tint_weight) + tg * tint_weight),
        clamp(bb * (1 - tint_weight) + tb * tint_weight),
    ))


def pick(palette: dict[str, str], key: str, fallback: str) -> str:
    value = palette.get(key) or fallback
    if not isinstance(value, str):
        return fallback
    return value


def build_theme(palette: dict[str, str], mix_weight: float) -> str:
    m = lambda tokyo_key, matugen_key, weight=mix_weight: mix(
        TOKYO_MOON[tokyo_key],
        pick(palette, matugen_key, TOKYO_MOON[tokyo_key]),
        weight,
    )

    # Slightly lower background tint keeps the terminal from changing personality
    # every time the wallpaper sneezes.
    background = mix(TOKYO_MOON["bg"], pick(palette, "background", TOKYO_MOON["bg"]), 0.28)
    foreground = mix(TOKYO_MOON["fg"], pick(palette, "on_surface", TOKYO_MOON["fg"]), 0.35)

    colors = {
        "background": background,
        "foreground": foreground,
        "cursor_color": m("blue", "primary", 0.55),
        "cursor_text": mix(TOKYO_MOON["bg_dark"], pick(palette, "on_primary", TOKYO_MOON["bg_dark"]), 0.35),
        "selection_background": mix(TOKYO_MOON["bg_highlight"], pick(palette, "secondary_container", TOKYO_MOON["bg_highlight"]), 0.45),
        "selection_foreground": mix(TOKYO_MOON["fg"], pick(palette, "on_secondary_container", TOKYO_MOON["fg"]), 0.35),

        # ANSI normal
        "black": mix(TOKYO_MOON["bg_dark"], pick(palette, "surface_container_highest", TOKYO_MOON["bg_dark"]), 0.35),
        "red": m("red", "error", 0.45),
        "green": m("green", "primary", 0.35),
        "yellow": m("yellow", "tertiary", 0.35),
        "blue": m("blue", "primary", 0.45),
        "magenta": m("magenta", "secondary", 0.45),
        "cyan": m("cyan", "tertiary", 0.35),
        "white": mix(TOKYO_MOON["fg"], pick(palette, "on_surface_variant", TOKYO_MOON["fg"]), 0.30),

        # ANSI bright
        "bright_black": mix(TOKYO_MOON["comment"], pick(palette, "outline", TOKYO_MOON["comment"]), 0.35),
        "bright_red": m("red", "error_container", 0.35),
        "bright_green": m("green", "primary_container", 0.35),
        "bright_yellow": m("yellow", "tertiary_container", 0.35),
        "bright_blue": m("blue", "primary_fixed_dim", 0.40),
        "bright_magenta": m("magenta", "secondary_fixed_dim", 0.40),
        "bright_cyan": m("cyan", "tertiary_fixed_dim", 0.40),
        "bright_white": foreground,
    }

    lines = [
        "# Ghostty theme: Matugen Moon",
        "# Generated by matugen-ghostty-moonmix.py.",
        "# Tokyonight Moon base, Matugen wallpaper mood. Civilized, allegedly.",
        "",
        f"background = {colors['background']}",
        f"foreground = {colors['foreground']}",
        "",
        f"cursor-color = {colors['cursor_color']}",
        f"cursor-text = {colors['cursor_text']}",
        "",
        f"selection-background = {colors['selection_background']}",
        f"selection-foreground = {colors['selection_foreground']}",
        "",
        f"palette = 0={colors['black']}",
        f"palette = 1={colors['red']}",
        f"palette = 2={colors['green']}",
        f"palette = 3={colors['yellow']}",
        f"palette = 4={colors['blue']}",
        f"palette = 5={colors['magenta']}",
        f"palette = 6={colors['cyan']}",
        f"palette = 7={colors['white']}",
        f"palette = 8={colors['bright_black']}",
        f"palette = 9={colors['bright_red']}",
        f"palette = 10={colors['bright_green']}",
        f"palette = 11={colors['bright_yellow']}",
        f"palette = 12={colors['bright_blue']}",
        f"palette = 13={colors['bright_magenta']}",
        f"palette = 14={colors['bright_cyan']}",
        f"palette = 15={colors['bright_white']}",
        "",
    ]

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a Ghostty Tokyonight Moon + Matugen mixed theme."
    )
    parser.add_argument("--palette", required=True, type=Path, help="Matugen-generated palette JSON.")
    parser.add_argument("--output", required=True, type=Path, help="Ghostty theme output path.")
    parser.add_argument(
        "--mix-weight",
        type=float,
        default=0.40,
        help="Default Matugen tint weight for most colors. 0.0 = Tokyonight, 1.0 = Matugen.",
    )
    args = parser.parse_args()

    if not 0 <= args.mix_weight <= 1:
        raise SystemExit("--mix-weight must be between 0.0 and 1.0")

    palette = json.loads(args.palette.expanduser().read_text(encoding="utf-8"))
    theme = build_theme(palette, args.mix_weight)

    output = args.output.expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(theme, encoding="utf-8")


if __name__ == "__main__":
    main()
